server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5435/burgerDb
spring.datasource.username=postgres
spring.datasource.password=168923
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.jdbc.bind=TRACE